"""Gerber ingest tests.

The reference test compares a Gerber set against the KiCad file it was exported from. That
comparison is the only thing that can catch the failure this path is prone to: a board that
parses, renders and lists nets, but has those nets attached to the wrong copper. Counts
alone do not catch it — routed length per net does, because it depends on geometry and net
assignment agreeing at once.

The fixtures are generated by ``scripts/make_gerber_fixture.py`` from the same
``tiny.kicad_pcb`` the KiCad tests use.

The fixture is a real board: a split ground plane on B.Cu with a 10 mm channel between the
halves, and a CLK trace crossing that channel. Everything on it clears everything else, so
both paths must reconstruct it identically and report no shorts.

It is deliberately expressed as two convex pours rather than one pour with a void. KiCad's
exporter re-plots a zone's outline rather than its stored fill, so a hand-written outline
that bridges into a hole does not survive the round trip — the pour comes back solid and the
exported board is one that could not be built. Two rectangles say the same thing about the
physics and export faithfully.

The same comparison runs against real hardware with ``scripts/compare_ingest.py``; on this
repo's 4-layer ``solar-ppm`` it reports 307 of 307 tracks named, no shorts, and every shared
net agreeing to 0.0%.
"""

from __future__ import annotations

import io
import math
import zipfile
from pathlib import Path

import pytest

from emi_worker import topology
from emi_worker.gerber import GerberError, load_gerber_board
from emi_worker.gerber.connectivity import _inside
from emi_worker.gerber.drill import parse_drill, parse_holes
from emi_worker.gerber.reader import _read_layer
from emi_worker.kicad import geometry as g
from emi_worker.gerber.ipcd356 import NetlistError, parse as parse_netlist
from emi_worker.kicad import parse, parse_board
from emi_worker.kicad.normalize import normalize
from emi_worker.raster import label_components, rasterize_rings
from emi_worker.rules import emc
from emi_worker.stages.ingest import load_board

FIXTURES = Path(__file__).parent / "fixtures"
GERBER_DIR = FIXTURES / "gerber"

pytestmark = pytest.mark.skipif(
    not GERBER_DIR.is_dir(),
    reason="gerber fixtures not generated (run scripts/make_gerber_fixture.py)",
)


@pytest.fixture(scope="module")
def gerber_files() -> dict[str, bytes]:
    return {p.name: p.read_bytes() for p in GERBER_DIR.iterdir() if p.is_file()}


@pytest.fixture(scope="module")
def gerber_board(gerber_files):
    return load_gerber_board(gerber_files)


@pytest.fixture(scope="module")
def kicad_board():
    return parse_board(parse((FIXTURES / "tiny.kicad_pcb").read_text()))


# ---- netlist -------------------------------------------------------------------------

def test_netlist_units_are_required():
    """Guessing the scale would silently resize the whole board."""
    with pytest.raises(NetlistError, match="units"):
        parse_netlist(_record("GND", "VIA", "", "A00X+001000Y+002000", "317") + "\n")


def test_netlist_reads_inch_units():
    text = "P  UNITS CUST 0\n" + _record("GND", "VIA", "", "A00X+010000Y+020000", "317") + "\n"
    n = parse_netlist(text)
    assert len(n.points) == 1
    # 10000 units at 0.0001 inch = 1 inch = 25.4 mm.
    assert n.points[0].x_mm == pytest.approx(25.4)
    assert n.points[0].y_mm == pytest.approx(50.8)


def _record(net: str, ref: str, pin: str, tail: str, kind: str = "327") -> str:
    """Build a record by column, so the test exercises the parser and not a typo."""
    return f"{kind}{net:<14}   {ref:<6}-{pin:<4} {tail}"


def test_netlist_reads_metric_units():
    text = "P  UNITS CUST 1\n" + _record("SIG", "U1", "1", "A01X+0012500Y+0025000") + "\n"
    n = parse_netlist(text)
    assert n.points[0].x_mm == pytest.approx(12.5)
    assert n.points[0].access == 1
    assert n.points[0].ref == "U1"
    assert n.points[0].pin == "1"


def test_netlist_rejects_an_empty_file():
    with pytest.raises(NetlistError):
        parse_netlist("P  UNITS CUST 1\nC comment only\n")


def test_long_net_names_are_flagged_as_truncated():
    """The format's net field is 14 characters, so names get cut by the exporter."""
    text = ("P  UNITS CUST 1\n"
            + _record("ABCDEFGHIJKLMN", "VIA", "", "A00X+0001000Y+0002000", "317") + "\n")
    n = parse_netlist(text)
    assert any("14-character" in w for w in n.warnings)


# ---- drill ---------------------------------------------------------------------------

def test_drill_reads_metric_tools():
    text = "M48\nMETRIC\nT1C0.300\n%\nT1\nX10.0Y20.0\nM30\n"
    vias, _ = parse_drill(text, ["F.Cu", "B.Cu"])
    assert len(vias) == 1
    assert vias[0].drill_mm == pytest.approx(0.3)
    assert vias[0].x == pytest.approx(10.0)
    # Excellon Y points up; the model uses KiCad's Y-down convention.
    assert vias[0].y == pytest.approx(-20.0)


def test_unplated_holes_are_not_conductors():
    """A mounting hole joins nothing; treating it as a via invents layer connections."""
    text = (
        "M48\nMETRIC\nT1C3.200\n%\n"
        "; #@! TA.AperFunction,NonPlated,NPTH\nTYPE=NON_PLATED\nT1\nX5.0Y5.0\nM30\n"
    )
    vias, _ = parse_drill(text, ["F.Cu", "B.Cu"])
    assert vias == []


# ---- raster --------------------------------------------------------------------------

def test_rasterise_and_label_separates_islands():
    a = [(1.0, 1.0), (3.0, 1.0), (3.0, 3.0), (1.0, 3.0)]
    b = [(6.0, 1.0), (8.0, 1.0), (8.0, 3.0), (6.0, 3.0)]
    mask = rasterize_rings([a, b], (0.0, 0.0), (100, 200), 0.05)
    labels, count = label_components(mask)
    assert count == 2
    assert labels[int(2 / 0.05), int(2 / 0.05)] != labels[int(2 / 0.05), int(7 / 0.05)]


def test_touching_shapes_are_one_island():
    a = [(1.0, 1.0), (3.0, 1.0), (3.0, 3.0), (1.0, 3.0)]
    b = [(2.5, 1.0), (5.0, 1.0), (5.0, 3.0), (2.5, 3.0)]
    mask = rasterize_rings([a, b], (0.0, 0.0), (100, 200), 0.05)
    _, count = label_components(mask)
    assert count == 1


# ---- the reference comparison ----------------------------------------------------------

def test_same_board_both_ways(gerber_board, kicad_board):
    """The Gerber path must describe the same board as the KiCad file it came from."""
    gdoc, _ = normalize(gerber_board, {})
    kdoc, _ = normalize(kicad_board, {})

    assert gerber_board.copper_layer_names == kicad_board.copper_layer_names
    assert gdoc["board"]["width_mm"] == pytest.approx(kdoc["board"]["width_mm"], abs=0.3)
    assert gdoc["board"]["height_mm"] == pytest.approx(kdoc["board"]["height_mm"], abs=0.3)


def test_net_lengths_agree(gerber_board, kicad_board):
    """Routed length per net is the check that matters.

    It depends on the geometry and the net assignment being right *together*: copper in the
    wrong place, or the right copper on the wrong net, both move these numbers. Counts of
    nets and tracks can match while every net is mislabelled.
    """
    gdoc, _ = normalize(gerber_board, {})
    kdoc, _ = normalize(kicad_board, {})

    def lengths(doc):
        # IPC-D-356 truncates and uppercases net names, so compare case-insensitively on
        # the tail of the name, which is the part the format keeps.
        return {
            n["name"].upper()[-12:]: n["length_mm"]
            for n in doc["nets"] if n["length_mm"] > 1.0
        }

    g, k = lengths(gdoc), lengths(kdoc)
    shared = set(g) & set(k)
    assert shared, f"no nets in common: {sorted(g)[:5]} vs {sorted(k)[:5]}"

    for name in shared:
        assert g[name] == pytest.approx(k[name], rel=0.05), (
            f"{name}: gerber {g[name]:.1f} mm vs kicad {k[name]:.1f} mm"
        )


def test_every_track_gets_a_net(gerber_board):
    """An unnamed track means net reconstruction failed for it."""
    named = sum(1 for t in gerber_board.tracks if t.net)
    assert named == len(gerber_board.tracks), (
        f"only {named} of {len(gerber_board.tracks)} tracks were matched to a net"
    )


def test_no_nets_share_copper(gerber_board):
    """Two nets on one island means the raster bridged copper that is really separate.

    The fixture is a manufacturable board with clearance everywhere, so any conflict here is
    a defect in the reader, not in the board.
    """
    conflicts = [w for w in gerber_board.warnings if "resolve to the same" in w]
    assert not conflicts, conflicts[:3]


def test_stackup_thickness_comes_from_the_job_file(gerber_board):
    dielectrics = [s for s in gerber_board.stackup if s.is_dielectric]
    assert dielectrics, "no dielectric layers were read"
    # Thicknesses are real; permittivity never is on this path.
    assert all(not s.from_file for s in dielectrics)
    assert any("permittivity" in w for w in gerber_board.warnings)


# ---- refusals --------------------------------------------------------------------------

def test_a_gerber_set_without_a_netlist_is_refused(gerber_files):
    """Without names there is no net picker and no way to place a port by net."""
    without = {n: b for n, b in gerber_files.items() if not n.lower().endswith(".d356")}
    with pytest.raises(GerberError, match="IPC-D-356"):
        load_gerber_board(without)


def test_archive_detection_picks_the_gerber_path(gerber_files):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, blob in gerber_files.items():
            z.writestr(f"fab/{name}", blob)
    model, _, kind = load_board(buf.getvalue())
    assert kind == "gerber"
    assert model.copper_layer_names


def test_archive_detection_prefers_a_kicad_file(gerber_files):
    """A project zip holding both should use the richer source."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, blob in gerber_files.items():
            z.writestr(f"fab/{name}", blob)
        z.writestr("tiny.kicad_pcb", (FIXTURES / "tiny.kicad_pcb").read_bytes())
    _, _, kind = load_board(buf.getvalue())
    assert kind == "kicad"


# ---- units ---------------------------------------------------------------------------

INCH_DIR = FIXTURES / "gerber_inch"


def test_an_inch_gerber_set_is_read_in_millimetres():
    """gerbonara returns the file's own unit; a %MOIN% board used to come back 25.4x small.

    The fixture is hand-written in inches: a 2 x 1 inch board, a one-inch SIG trace 10 mil
    wide between two 40 x 60 mil pads, and a GND pour with a via.
    """
    model = load_gerber_board({p.name: p.read_bytes() for p in INCH_DIR.iterdir()})

    sig = [t for t in model.tracks if t.net == "SIG"]
    assert len(sig) == 1
    assert sig[0].length_mm == pytest.approx(25.4)
    assert sig[0].width_mm == pytest.approx(0.254)

    pads = {f"{p.ref}.{p.number}": p for p in model.pads}
    assert set(pads) == {"U1.1", "U2.1"}
    xs = [x for x, _ in pads["U1.1"].ring]
    ys = [y for _, y in pads["U1.1"].ring]
    assert max(xs) - min(xs) == pytest.approx(1.016)
    assert max(ys) - min(ys) == pytest.approx(1.524)

    outline = [p for ring in model.outline for p in ring]
    assert max(x for x, _ in outline) - min(x for x, _ in outline) == pytest.approx(50.8)
    assert max(y for _, y in outline) - min(y for _, y in outline) == pytest.approx(25.4)

    gnd = [z for z in model.zones if z.net == "GND"]
    assert gnd and abs(g.signed_area(gnd[0].ring)) == pytest.approx(45.72 * 6.35)
    assert [v.net for v in model.vias] == ["GND"]
    assert model.vias[0].drill_mm == pytest.approx(0.381)

    topo = topology.build(model)
    assert topo["SIG"].path("U1.1", "U2.1").length_mm == pytest.approx(25.4)


# ---- parts from the netlist ------------------------------------------------------------

def test_gerber_pads_are_named_after_the_netlist(gerber_board, kicad_board):
    """Every ref-dependent check keyed on pads found nothing on a Gerber upload.

    IPC-D-356 names the component and pin at each point; they now land on the pad there.
    """
    named = sorted((p.ref, p.number, p.net) for p in gerber_board.pads if p.ref)
    assert named == [("J1", "1", "DATA"), ("U1", "1", "CLK"), ("U1", "2", "GND")]
    assert all(p.ref for p in gerber_board.pads), "anonymous pads left over"

    # J1 is through-hole: one pad on both layers, and its hole is not a via.
    j1 = next(p for p in gerber_board.pads if p.ref == "J1")
    assert j1.pad_type == "thru_hole"
    assert set(j1.layers) == {"F.Cu", "B.Cu"}
    assert len(gerber_board.vias) == len(kicad_board.vias)
    # The via's annular ring, flashed on copper, becomes its size.
    assert all(v.size_mm > v.drill_mm for v in gerber_board.vias)


def test_gerber_topology_and_parts_match_kicad(gerber_board, kicad_board):
    gt, kt = topology.build(gerber_board), topology.build(kicad_board)
    for net in ("CLK", "DATA", "GND"):
        assert (sorted(gt[net].pads), sorted(gt[net].unreachable)) == (
            sorted(kt[net].pads), sorted(kt[net].unreachable)), net

    # The EMC checks find connectors by reference designator.
    assert set(emc._Parts(gerber_board).connectors) == {"J1"}
    assert set(emc._Parts(gerber_board).connectors) == set(emc._Parts(kicad_board).connectors)


# ---- drill files -------------------------------------------------------------------------

_NPTH = """M48
; DRILL file KiCad 10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.0Y-37.0
M30
"""


@pytest.mark.parametrize("npth_first", [True, False])
def test_every_drill_file_is_read_in_either_order(gerber_files, npth_first):
    """KiCad writes PTH and NPTH separately. Keeping only the last one lost every via."""
    files = {n: b for n, b in gerber_files.items() if not n.endswith(".drl")}
    pth = ("tiny-PTH.drl", gerber_files["tiny.drl"])
    npth = ("tiny-NPTH.drl", _NPTH.encode())
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, blob in ([npth, pth] if npth_first else [pth, npth]):
            z.writestr(name, blob)
        for name, blob in files.items():
            z.writestr(name, blob)
    model, _, _ = load_board(buf.getvalue())

    assert sorted((v.x, v.y) for v in model.vias) == [(6.0, 6.0), (16.0, 2.0), (25.0, 20.0)]
    # The mounting hole is not a via, and is not a pad either: it has no copper.
    assert all(math.dist((v.x, v.y), (3.0, 37.0)) > 1 for v in model.vias)


def test_plating_is_read_per_tool_in_a_mixed_file():
    text = (
        "M48\n; #@! TF.FileFunction,MixedPlating,1,2\nMETRIC\n"
        "; #@! TA.AperFunction,Plated,PTH,ViaDrill\nT1C0.300\n"
        "; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill\nT2C3.200\n"
        "%\nT1\nX1.0Y-1.0\nT2\nX5.0Y-5.0\nM30\n"
    )
    holes, _ = parse_holes(text)
    assert [(h.plated, h.function) for h in holes] == [(True, "via"), (False, "component")]
    vias, _ = parse_drill(text, ["F.Cu", "B.Cu"])
    assert [(v.x, v.y) for v in vias] == [(1.0, 1.0)]


def test_an_npth_file_alone_has_no_vias():
    holes, _ = parse_holes(_NPTH)
    assert len(holes) == 1 and not holes[0].plated


# ---- clear polarity and negative images --------------------------------------------------

_HEAD = "%FSLAX46Y46*%\n%MOMM*%\nG01*\n%ADD10C,2.000000*%\n%ADD11C,1.000000*%\n"
_POUR = "G36*\nX0Y0D02*\nX10000000Y0D01*\nX10000000Y10000000D01*\nX0Y10000000D01*\nX0Y0D01*\nG37*\n"


def _covered(zones, x, y):
    """Whether a model point is copper, filling each zone ring even-odd like the raster."""
    return any(_inside(x, y, z.ring) for z in zones)


def test_clear_shapes_are_cut_out_of_a_pour():
    """%LPC% anti-pads were filled in as copper, joining a via to the plane around it."""
    text = (_HEAD + "%LPD*%\n" + _POUR
            + "%LPC*%\nD10*\nX5000000Y5000000D03*\nX2000000Y2000000D03*\n"
            + "%LPD*%\nD11*\nX5000000Y5000000D03*\nM02*\n")
    warnings: list[str] = []
    _, pads, zones = _read_layer(text, "In1.Cu", warnings)
    assert len(zones) == 1 and len(pads) == 1
    # Two holes of r = 1 mm cut from a 10 x 10 mm pour.
    assert abs(g.signed_area(zones[0].ring)) == pytest.approx(100 - 2 * math.pi, rel=0.01)
    assert not _covered(zones, 5.7, -5.0)      # inside the anti-pad, outside the via pad
    assert _covered(zones, 5.0, -8.0)          # plane
    assert not warnings

    # The via pad sits in the hole as its own island, apart from the plane.
    mask = rasterize_rings([z.ring for z in zones] + [pads[0].ring],
                           (-1.0, -11.0), (240, 240), 0.05)
    _, count = label_components(mask)
    assert count == 2


@pytest.mark.filterwarnings("ignore:.*IPNEG.*:DeprecationWarning")
@pytest.mark.parametrize("marker", ["%TF.FilePolarity,Negative*%\n", "%IPNEG*%\n"])
def test_a_negative_plane_is_copper_except_where_it_draws(marker):
    text = marker + _HEAD + "%LPD*%\nD10*\nX5000000Y5000000D03*\nM02*\n"
    _, pads, zones = _read_layer(text, "In1.Cu", [], extent=(0.0, -10.0, 10.0, 0.0))
    assert not pads, "a drawn shape on a negative image is a clearance, not copper"
    assert len(zones) == 1
    assert abs(g.signed_area(zones[0].ring)) == pytest.approx(100 - math.pi, rel=0.01)
    assert not _covered(zones, 5.0, -5.0)
    assert _covered(zones, 1.0, -1.0)


def test_a_clear_shape_that_cannot_be_cut_is_reported():
    """A clear line splitting the pour needs polygon clipping; say so rather than be wrong."""
    text = (_HEAD + "%LPD*%\n" + _POUR
            + "%LPC*%\nD11*\nX5000000Y-1000000D02*\nX5000000Y11000000D01*\nM02*\n")
    warnings: list[str] = []
    _read_layer(text, "In1.Cu", warnings)
    assert any("could not be applied" in w for w in warnings)
