"""Gerber ingest tests.

The reference test compares a Gerber set against the KiCad file it was exported from. That
comparison is the only thing that can catch the failure this path is prone to: a board that
parses, renders and lists nets, but has those nets attached to the wrong copper. Counts
alone do not catch it — routed length per net does, because it depends on geometry and net
assignment agreeing at once.

The fixtures are generated by ``scripts/make_gerber_fixture.py`` from the same
``tiny.kicad_pcb`` the KiCad tests use.

The fixture is a real board: a split ground plane on B.Cu with a 10 mm channel between the
halves, and a CLK trace crossing that channel. Everything on it clears everything else, so
both paths must reconstruct it identically and report no shorts.

It is deliberately expressed as two convex pours rather than one pour with a void. KiCad's
exporter re-plots a zone's outline rather than its stored fill, so a hand-written outline
that bridges into a hole does not survive the round trip — the pour comes back solid and the
exported board is one that could not be built. Two rectangles say the same thing about the
physics and export faithfully.

The same comparison runs against real hardware with ``scripts/compare_ingest.py``; on this
repo's 4-layer ``solar-ppm`` it reports 307 of 307 tracks named, no shorts, and every shared
net agreeing to 0.0%.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

from emi_worker.gerber import GerberError, load_gerber_board
from emi_worker.gerber.drill import parse_drill
from emi_worker.gerber.ipcd356 import NetlistError, parse as parse_netlist
from emi_worker.kicad import parse, parse_board
from emi_worker.kicad.normalize import normalize
from emi_worker.raster import label_components, rasterize_rings
from emi_worker.stages.ingest import load_board

FIXTURES = Path(__file__).parent / "fixtures"
GERBER_DIR = FIXTURES / "gerber"

pytestmark = pytest.mark.skipif(
    not GERBER_DIR.is_dir(),
    reason="gerber fixtures not generated (run scripts/make_gerber_fixture.py)",
)


@pytest.fixture(scope="module")
def gerber_files() -> dict[str, bytes]:
    return {p.name: p.read_bytes() for p in GERBER_DIR.iterdir() if p.is_file()}


@pytest.fixture(scope="module")
def gerber_board(gerber_files):
    return load_gerber_board(gerber_files)


@pytest.fixture(scope="module")
def kicad_board():
    return parse_board(parse((FIXTURES / "tiny.kicad_pcb").read_text()))


# ---- netlist -------------------------------------------------------------------------

def test_netlist_units_are_required():
    """Guessing the scale would silently resize the whole board."""
    with pytest.raises(NetlistError, match="units"):
        parse_netlist(_record("GND", "VIA", "", "A00X+001000Y+002000", "317") + "\n")


def test_netlist_reads_inch_units():
    text = "P  UNITS CUST 0\n" + _record("GND", "VIA", "", "A00X+010000Y+020000", "317") + "\n"
    n = parse_netlist(text)
    assert len(n.points) == 1
    # 10000 units at 0.0001 inch = 1 inch = 25.4 mm.
    assert n.points[0].x_mm == pytest.approx(25.4)
    assert n.points[0].y_mm == pytest.approx(50.8)


def _record(net: str, ref: str, pin: str, tail: str, kind: str = "327") -> str:
    """Build a record by column, so the test exercises the parser and not a typo."""
    return f"{kind}{net:<14}   {ref:<6}-{pin:<4} {tail}"


def test_netlist_reads_metric_units():
    text = "P  UNITS CUST 1\n" + _record("SIG", "U1", "1", "A01X+0012500Y+0025000") + "\n"
    n = parse_netlist(text)
    assert n.points[0].x_mm == pytest.approx(12.5)
    assert n.points[0].access == 1
    assert n.points[0].ref == "U1"
    assert n.points[0].pin == "1"


def test_netlist_rejects_an_empty_file():
    with pytest.raises(NetlistError):
        parse_netlist("P  UNITS CUST 1\nC comment only\n")


def test_long_net_names_are_flagged_as_truncated():
    """The format's net field is 14 characters, so names get cut by the exporter."""
    text = ("P  UNITS CUST 1\n"
            + _record("ABCDEFGHIJKLMN", "VIA", "", "A00X+0001000Y+0002000", "317") + "\n")
    n = parse_netlist(text)
    assert any("14-character" in w for w in n.warnings)


# ---- drill ---------------------------------------------------------------------------

def test_drill_reads_metric_tools():
    text = "M48\nMETRIC\nT1C0.300\n%\nT1\nX10.0Y20.0\nM30\n"
    vias, _ = parse_drill(text, ["F.Cu", "B.Cu"])
    assert len(vias) == 1
    assert vias[0].drill_mm == pytest.approx(0.3)
    assert vias[0].x == pytest.approx(10.0)
    # Excellon Y points up; the model uses KiCad's Y-down convention.
    assert vias[0].y == pytest.approx(-20.0)


def test_unplated_holes_are_not_conductors():
    """A mounting hole joins nothing; treating it as a via invents layer connections."""
    text = (
        "M48\nMETRIC\nT1C3.200\n%\n"
        "; #@! TA.AperFunction,NonPlated,NPTH\nTYPE=NON_PLATED\nT1\nX5.0Y5.0\nM30\n"
    )
    vias, _ = parse_drill(text, ["F.Cu", "B.Cu"])
    assert vias == []


# ---- raster --------------------------------------------------------------------------

def test_rasterise_and_label_separates_islands():
    a = [(1.0, 1.0), (3.0, 1.0), (3.0, 3.0), (1.0, 3.0)]
    b = [(6.0, 1.0), (8.0, 1.0), (8.0, 3.0), (6.0, 3.0)]
    mask = rasterize_rings([a, b], (0.0, 0.0), (100, 200), 0.05)
    labels, count = label_components(mask)
    assert count == 2
    assert labels[int(2 / 0.05), int(2 / 0.05)] != labels[int(2 / 0.05), int(7 / 0.05)]


def test_touching_shapes_are_one_island():
    a = [(1.0, 1.0), (3.0, 1.0), (3.0, 3.0), (1.0, 3.0)]
    b = [(2.5, 1.0), (5.0, 1.0), (5.0, 3.0), (2.5, 3.0)]
    mask = rasterize_rings([a, b], (0.0, 0.0), (100, 200), 0.05)
    _, count = label_components(mask)
    assert count == 1


# ---- the reference comparison ----------------------------------------------------------

def test_same_board_both_ways(gerber_board, kicad_board):
    """The Gerber path must describe the same board as the KiCad file it came from."""
    gdoc, _ = normalize(gerber_board, {})
    kdoc, _ = normalize(kicad_board, {})

    assert gerber_board.copper_layer_names == kicad_board.copper_layer_names
    assert gdoc["board"]["width_mm"] == pytest.approx(kdoc["board"]["width_mm"], abs=0.3)
    assert gdoc["board"]["height_mm"] == pytest.approx(kdoc["board"]["height_mm"], abs=0.3)


def test_net_lengths_agree(gerber_board, kicad_board):
    """Routed length per net is the check that matters.

    It depends on the geometry and the net assignment being right *together*: copper in the
    wrong place, or the right copper on the wrong net, both move these numbers. Counts of
    nets and tracks can match while every net is mislabelled.
    """
    gdoc, _ = normalize(gerber_board, {})
    kdoc, _ = normalize(kicad_board, {})

    def lengths(doc):
        # IPC-D-356 truncates and uppercases net names, so compare case-insensitively on
        # the tail of the name, which is the part the format keeps.
        return {
            n["name"].upper()[-12:]: n["length_mm"]
            for n in doc["nets"] if n["length_mm"] > 1.0
        }

    g, k = lengths(gdoc), lengths(kdoc)
    shared = set(g) & set(k)
    assert shared, f"no nets in common: {sorted(g)[:5]} vs {sorted(k)[:5]}"

    for name in shared:
        assert g[name] == pytest.approx(k[name], rel=0.05), (
            f"{name}: gerber {g[name]:.1f} mm vs kicad {k[name]:.1f} mm"
        )


def test_every_track_gets_a_net(gerber_board):
    """An unnamed track means net reconstruction failed for it."""
    named = sum(1 for t in gerber_board.tracks if t.net)
    assert named == len(gerber_board.tracks), (
        f"only {named} of {len(gerber_board.tracks)} tracks were matched to a net"
    )


def test_no_nets_share_copper(gerber_board):
    """Two nets on one island means the raster bridged copper that is really separate.

    The fixture is a manufacturable board with clearance everywhere, so any conflict here is
    a defect in the reader, not in the board.
    """
    conflicts = [w for w in gerber_board.warnings if "resolve to the same" in w]
    assert not conflicts, conflicts[:3]


def test_stackup_thickness_comes_from_the_job_file(gerber_board):
    dielectrics = [s for s in gerber_board.stackup if s.is_dielectric]
    assert dielectrics, "no dielectric layers were read"
    # Thicknesses are real; permittivity never is on this path.
    assert all(not s.from_file for s in dielectrics)
    assert any("permittivity" in w for w in gerber_board.warnings)


# ---- refusals --------------------------------------------------------------------------

def test_a_gerber_set_without_a_netlist_is_refused(gerber_files):
    """Without names there is no net picker and no way to place a port by net."""
    without = {n: b for n, b in gerber_files.items() if not n.lower().endswith(".d356")}
    with pytest.raises(GerberError, match="IPC-D-356"):
        load_gerber_board(without)


def test_archive_detection_picks_the_gerber_path(gerber_files):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, blob in gerber_files.items():
            z.writestr(f"fab/{name}", blob)
    model, _, kind = load_board(buf.getvalue())
    assert kind == "gerber"
    assert model.copper_layer_names


def test_archive_detection_prefers_a_kicad_file(gerber_files):
    """A project zip holding both should use the richer source."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        for name, blob in gerber_files.items():
            z.writestr(f"fab/{name}", blob)
        z.writestr("tiny.kicad_pcb", (FIXTURES / "tiny.kicad_pcb").read_bytes())
    _, _, kind = load_board(buf.getvalue())
    assert kind == "kicad"
