"""Install this checkout into KiCad as a development copy of the plugin.

The copy sits beside a released install from the Plugin and Content Manager instead of
replacing it: its own identifier (".dev"), its own name ("(dev)"), its own Python environment
and its own window. Both buttons appear in the PCB Editor, and the dev one runs this
checkout.

The folder holds only what KiCad reads directly: plugin.json, the icons and requirements.txt,
copied, and one entry script that imports the plugin from this checkout. No symlinks, so
nothing depends on how KiCad resolves them. Python changes take effect on the next button
press.

    python scripts/dev_install.py [--plugins DIR] [--uninstall]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

PLUGIN = Path(__file__).resolve().parent.parent
FOLDER = "emi-analyzer-dev"
MARKER = ".dev-install"

ENTRY = '''"""Development copy: open the EMI Analyzer on the board in the editor.

Runs the plugin from {src}. Generated by scripts/dev_install.py.
"""

import sys
from pathlib import Path

sys.path.insert(0, {src!r})

# PySide6 is a few hundred megabytes, and KiCad installs a plugin's requirements into an
# environment of its own, per plugin identifier. Rather than download it a second time for
# this copy, borrow it from another plugin's environment: the released copy of this one
# first, then any other that has it. requirements.txt here asks only for kicad-python, so
# nothing heavy is installed twice.
try:
    import PySide6  # noqa: F401
except ImportError:
    envs = Path({envs!r})
    for base in [envs] + sorted(p for p in envs.parent.glob("*") if p != envs):
        sites = sorted(base.glob("lib/python*/site-packages"))
        if any((s / "PySide6").is_dir() for s in sites):
            sys.path.extend(str(s) for s in sites)
            break

from emi_analyzer.app import analyze  # noqa: E402

if __name__ == "__main__":
    sys.exit(analyze())
'''


def default_plugins_dir() -> Path:
    home = Path.home()
    if sys.platform in ("darwin", "win32"):
        return home / "Documents" / "KiCad" / "10.0" / "plugins"
    return home / ".local" / "share" / "kicad" / "10.0" / "plugins"


def dev_manifest(release: dict) -> dict:
    m = json.loads(json.dumps(release))
    m["identifier"] = release["identifier"] + ".dev"
    m["name"] = release["name"] + " (dev)"
    for a in m["actions"]:
        a["name"] = a["name"] + " (dev)"
        a["description"] = a["description"] + " (development copy)"
    return m


def release_env(identifier: str) -> Path:
    """The Python environment KiCad made for the released plugin.

    It may not exist, and neither may the folder it sits in; the entry script only looks
    there if PySide6 is missing from the development copy's own environment, and it falls
    back to any other plugin's environment that has PySide6.
    """
    if sys.platform == "darwin":
        base = Path.home() / "Library" / "Caches" / "kicad"
    elif sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home())) / "kicad"
    else:
        base = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "kicad"
    return base / "10.0" / "python-environments" / identifier


def install(plugins: Path) -> Path:
    target = plugins / FOLDER
    if target.exists() and not (target / MARKER).exists():
        raise SystemExit(f"{target} exists and was not made by this script; remove it first")
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    release = json.loads((PLUGIN / "plugin.json").read_text())
    (target / "plugin.json").write_text(json.dumps(dev_manifest(release), indent=2) + "\n")
    # Only the small dependency: PySide6 comes from the released plugin's environment (see
    # the entry script), or from this one if it is there.
    (target / "requirements.txt").write_text(
        "# Development copy. PySide6 is taken from the released plugin's environment\n"
        "# when it has one; see analyze.py.\n"
        "kicad-python>=0.7.0\n"
    )
    shutil.copytree(PLUGIN / "icons", target / "icons")
    (target / "analyze.py").write_text(
        ENTRY.format(src=str(PLUGIN), envs=str(release_env(release["identifier"])))
    )
    (target / MARKER).write_text(f"source: {PLUGIN}\n")
    return target


def uninstall(plugins: Path) -> None:
    target = plugins / FOLDER
    if (target / MARKER).exists():
        shutil.rmtree(target)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--plugins", type=Path, default=default_plugins_dir())
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args()
    if args.uninstall:
        uninstall(args.plugins)
        print(f"removed {args.plugins / FOLDER}")
        return 0
    target = install(args.plugins)
    print(f"installed {target}")
    print("restart KiCad (or Preferences -> Plugins -> Reload) the first time; after that, changes apply on the next press")
    return 0


if __name__ == "__main__":
    sys.exit(main())
