#!/bin/sh
# Writes the Homebrew cask for one release to stdout.
#
#   deploy/homebrew/render-cask.sh 0.3.0 SHA256SUMS > emi-analyzer.rb
#
# SHA256SUMS is the file attached to that release; the cask takes the checksums of
# the two macOS disk images from it. The homebrew workflow runs this when a release
# is published and pushes the result to embeddedci-com/homebrew-tap, so
#
#   brew install --cask embeddedci-com/tap/emi-analyzer
#
# installs the app. The app is not code-signed: the cask removes the download
# quarantine after installing, which is what makes it open without a Gatekeeper
# prompt.
set -eu

version=${1:?usage: render-cask.sh VERSION SHA256SUMS}
sums=${2:?usage: render-cask.sh VERSION SHA256SUMS}

sha() {
  s=$(awk -v f="$1" '$2 == f || $2 == "*" f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "render-cask.sh: $1 is not in $sums" >&2; exit 1; }
  echo "$s"
}
arm=$(sha "EMI.Analyzer_${version}_aarch64.dmg")
intel=$(sha "EMI.Analyzer_${version}_x64.dmg")

cat <<CASK
# Generated by deploy/homebrew/render-cask.sh in embeddedci-com/emi-analyzer on release.
# Edit it there, not here: the next release overwrites this file.
cask "emi-analyzer" do
  arch arm: "aarch64", intel: "x64"

  version "${version}"
  sha256 arm:   "${arm}",
         intel: "${intel}"

  url "https://github.com/embeddedci-com/emi-analyzer/releases/download/v#{version}/EMI.Analyzer_#{version}_#{arch}.dmg"
  name "EMI Analyzer"
  desc "Checks PCB layouts for the causes of EMI and EMC failures, on your own computer"
  homepage "https://github.com/embeddedci-com/emi-analyzer"

  livecheck do
    skip "Updated on release."
  end

  depends_on :macos

  app "EMI Analyzer.app"

  # Not code-signed yet: without this, macOS refuses to open the app.
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/EMI Analyzer.app"],
        must_succeed: false
  end

  zap trash: [
    "~/Library/Application Support/com.embeddedci.emi-analyzer",
    "~/Library/Application Support/emi-analyzer",
    "~/Library/Caches/com.embeddedci.emi-analyzer",
    "~/Library/WebKit/com.embeddedci.emi-analyzer",
  ]

  caveats <<~EOS
    EMI Analyzer runs its analysis in Docker. If you do not have Docker yet:
      brew install --cask docker-desktop
    or OrbStack:
      brew install --cask orbstack
  EOS
end
CASK
